alter table `gx_special` add `class` mediumint(8) DEFAULT 1;
alter table `gx_co_content` add `class` mediumint(5) DEFAULT 0;
alter table `gx_co_content` add `did` mediumint(5) DEFAULT 0;
alter table `gx_co_node` add `class` mediumint(5) DEFAULT 0;
alter table `gx_co_node` add `keymode` TINYINT(1) UNSIGNED NOT NULL DEFAULT 0;
alter table `gx_co_node` add `downmode` TINYINT(1) UNSIGNED NOT NULL DEFAULT 3;
alter table `gx_co_node` add `downlist_start` char(100) CHARACTER SET utf8 COLLATE utf8_general_ci;
alter table `gx_co_node` add `downlist_end` char(100) CHARACTER SET utf8 COLLATE utf8_general_ci;
alter table `gx_co_node` add `durl_range` TINYINT(1) UNSIGNED DEFAULT 2;
alter table `gx_co_node` add `downurl_start` char(100) CHARACTER SET utf8 COLLATE utf8_general_ci;
alter table `gx_co_node` add `downurl_end` char(100) CHARACTER SET utf8 COLLATE utf8_general_ci;
alter table `gx_co_node` add `downlink_rule` char(100) CHARACTER SET utf8 COLLATE utf8_general_ci;
alter table `gx_co_node` add `downlink_filter` text CHARACTER SET utf8 COLLATE utf8_general_ci;
alter table `gx_co_node` add `downurl_rule` char(100) CHARACTER SET utf8 COLLATE utf8_general_ci;
alter table `gx_co_node` add `downurl_filter` text CHARACTER SET utf8 COLLATE utf8_general_ci;
alter table `gx_video` add `downurl` longtext CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL;
alter table `gx_video` add `dlock` TINYINT(1) UNSIGNED NOT NULL DEFAULT 1;
alter table `gx_video` add `dbind` TINYINT(1) UNSIGNED NOT NULL DEFAULT 1;
alter table `gx_video` add `dreurl` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci;